### PR TITLE
Use imperative mood in commit subject examples

### PR DESCRIPTION
**Pull request by tcharding**
Typically we use imperative mood in commit subject lines, we should do so here in the examples.

Use imperative mood and also remove full stops from the git commit subject line examples.

### CODE REVIEW

**Comment by tcharding** [comment]
This tool looks awesome! Looking forward to having a play with it.

**Comment by crywolf** [comment]
Thanks Tobin, I agree. I need to fix some stuff first, so I will change the messages during that process as well.

**Comment by tcharding** [comment]
No worries man, thanks!

**Comment by tcharding** [comment]
I'll close this and leave it with you.

**Comment by Kixunil** [comment]
Just noticed this. I wonder if this is an argument against pushing imperative mode. While it's a custom in git, I think it looks weird for the user to read "Add foo to bar" rather than "Added foo to bar". I don't mind it in examples/tests of this project but what about real use? One may also just not use `inherit` but that could easily suck. I found that many messages are equally good in commits and for users (at least titles).

**Comment by tcharding** [comment]
> but what about real use

Oh man, I definitely don't want to fight this battle.

**Pull request closed without merging**
